import React, { Component } from 'react';
import './menu.css';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';
class Menu extends Component {
  render() {
    return (
      <Router>
        <nav>
          <ul>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/adventure'
              >
                Adventure
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/technology'
              >
                Technology
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/art'
              >
                Art
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/black&white'
              >
                Black & White
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/vintage'
              >
                Vintage
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/lifestyle'
              >
                Lifestyle
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/hip&healthy'
              >
                Hip & Healthy
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
                Dark
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
                Nature
              </Link>
            </li>
             <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
                Music
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
                Sports
              </Link>
            </li>
             <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
                Fashion
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
               Abstract Art
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
                Silhouettes
              </Link>
            </li>
            <li>
              <Link
                onClick={this.props.menuItemClicked}
                className='link'
                to='/dark'
              >
              Pink
              </Link>
            </li>
          </ul>
        </nav>
      </Router>
    );
  }
}

export default Menu;
